export const API_ERROR = 'API_ERROR_RECEIVED';
export const WEATHER_DATA_RECEIVED = 'WEATHER_DATA_RECEIVED';

export const METRICS_DATA_RECEIVED = 'METRICS_DATA_RECEIVED';
export const NEW_MEASUREMENTS_RECEIVED = 'NEW_MEASUREMENT_DATA_RECEIVED';
export const METRICS_MEASUREMENTS_RECEIVED = 'METRICS_MEASUREMENTS_RECEIVED';

export const NEW_MEASUREMENTS_API_CALL_FAIL = 'NEW_MEASUREMENTS_API_CALL_FAIL';
export const METRIC_API_CALL_FAIL = 'METRIC_API_CALL_FAIL';
export const MULTIPLE_MEASUREMENTS_API_CALL_FAIL = 'MULTIPLE_MEASUREMENTS_API_CALL_FAIL';
